name: Waka Stats

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: wakastats
          SHOW_SHORT_INFO: "False"
          DEBUG_LOGGING: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
